### ISSUE TITLE
Respond to market/exchange shutdown signal gracefully

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#153]
@mesalas will implement a feature of AMMPS such that if there's some anomaly that causes the exchange to shut down (i.e., negative prices due to sale of 1 billions shares), it sends a signal back with an 'error message' and a sign to stop.

SHARKFin needs to know what to do with this signal:
 - output the 'error' to the logs
 - shut down RabbitMQ, etc.

**Comment by mesalas** [comment]
Hi @sbenthall
Zach an I have implemented an "emergency" shutdown procedure in ammps that allows us to shutdown the market gracefully, close the rabbitMQ connection and finish writing logs. 

In order to message that ammps has stopped, I have changed the data sent from ammps to SHARKFin. Previously we just send the closing price, now we send a string of JSON containing the following fields: 

- `BuyTarget`: Buy target ammps got from sharkfin
- `SellTarget`: Sell target ammps got from sharkfin
- `ClosingPrice`: Ammps closing price (what we would send previously)
- `MarketState`: Ammps market state
- `NextDividend`: dividend ammps got from sharkfin

`BuyTarget`, `SellTarget` and `NextDividend` is the data ammps received from sharkfin at the beginning of the day, but i included it as we may want to check that it matches what was sent, or just for logging. we can also remove it, i have no strong feelings about this. 

In https://github.com/sbenthall/SHARKFin/tree/i153 , I have changed ammps.py market class to convert the json string to a dict and grab the "ClosingPrice", i have also implemented that the simulation continues as normal as long at the market state field is "normal". I have added an if statement for when the "MarketState" starts with "Stopped:" which is where we want to signal to sharkfin that the market has stopped. This means that we can extend the string with a reason for the shutdown, eg "Stopped: negative prices", which we can use for the logging or have different behavior according to the reason. 

Finally by sending a dictionary as the response allows us to easily add new information to be passed from ammps to sharkfin, eg broker positions, shortfalls etc.

Best regards
Nicholas

**Comment by sbenthall** [comment]
Hi Nicholas @mesalas ,

I'm trying to make progress on this, but the first thing I would typically do is replicate the original error, or the new errors due to the Market output changing).

Unfortunately, we do not yet have any automated testing framework for SHARKFin and the RPC market (this is issue #127), so this is somewhat tricky to do.

I am running the system locally now with `ammps_sharkfin_container` updated from that repository's `master` but I see the most recent changes to that branch are not very recent. So where did you put the new changes to the Market class? Are they in the container binaries yet?

**Comment by sbenthall** [comment]
I'm also trying to find condition that triggers the Market failure state, either using the original AMMPS or the updated one, so I can test the response to getting the failure signal.

By setting DPHM very very high, I was able to run a simulation that appears to have crashed at day 2/13. But there's no error output to the command line and it appears that both AMMPS and SHARKFin are both still running -- maybe just waiting.

Are there logs I can check to see if AMMPS has failed in the expected way?

**Comment by mesalas** [comment]
I Seb,

I agree that its super inconvenient to test the ammps sharkfin container. I think we should maybe set up a dedicated meeting for trying to figure out a good way of doing it, ideally how we can make some automated tests or something.

Ill try and describe the process I have used to Investigate the errors that Gary posted. 

What I call Error1 gives the following error message:

```
06/15/2017 00:00:00 : ABC Closing price 129.21 . Simulated in 25.684 seconds
06/16/2017 00:00:00 : ABC Closing price 130.87 . Simulated in 29.088 seconds
System.ArgumentException: An item with the same key has already been added. Key: 120
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at amm.core.com.ExternalRPCMarket.HarkRPCClient.TargetsReceived(Object model, BasicDeliverEventArgs ea) in /Users/nicholas/algofinance/amm.engine/amm.engine/amm.core/com/ExternalRPCMarket/HarkRPCClient.cs:line 93
```

the simulation ID is whiteshark-test0 and the corresponding yaml config that generates the error looks like this:
[whiteshark-test0_error.yml](https://gist.github.com/mesalas/67b3c8412f76bc67f219217e76eac4ad) (note that I have changed the ip of the rabbitMQ server used to host.docker.internal in order to point it at an internal docker container running rabbitMQ)

**Reproduce the error in Docker:**

1. pull the latest ammps_sharkfin_container and build it using `docker build --no-cache -t ammps_sharkfin:anysim .` the `-t` assigns a name to the container (in this case `ammps_sharkfin:anysim`)
2. Start a container running the rabbitMQ server using `docker run --rm -p 5672:5672 -p 15672:15672 rabbitmq:3-management`
3. Download [whiteshark-test0_error.yml](https://gist.github.com/mesalas/67b3c8412f76bc67f219217e76eac4ad) to an appropriate dir on the local maching
4. Start the simulation using`docker run --rm -e SIMSCONFIGPATH=output/whiteshark-test0_error.yml -v [local path to dir containing whiteshark-test0_error.yml]:/usr/simulation/output ammps_sharkfin:anysim`

This however does not help us uncover any new information, just reproduces the error.
We can run ammps and sharkfin together outside of the container, and in particular we can run each in a debugger which allows us to inspect whats going on at different points in the execution. 

**Reproduce the error outside of docker:**

To run sharkfin and ammps locally outside a container we need, a working version of Sharkfin targeting release 0.3, a local and compiled verion of ammps and a current version of [ammps_config_generator](https://github.com/mesalas/ammps_config_generator) and a running rabbitMQ Server container.

To reproduce the error we checkout the commit from which the ammps binaries in the latest ammps_sharkfin_container were built (c1f650d7bec30397df12fdb74897ce3435a49869)[https://github.com/ZDavid/amm.engine/commit/c1f650d7bec30397df12fdb74897ce3435a49869]. If we just want to run it (id not step through the code in a debugger) the binaries are built by navigating to the `amm.engine` dir and buidlig using `dotnet build -c Release amm.engine.sln` this should build ammps in `amm.engine/amm.engine/bin/Release/net6/`. To run it navigate to this directory and use `dotnet amm.engine.dll` (Note we need to apply some command line options. see below). 

Dissecting the yaml config leading to the error the following things happen.

1. ammps_config_generator is used to generate a configuration for ammps  with options: `--seed 92975 --name test_conf.xlsx --days 120 --out-dir /usr/simulation/`
2. ammps is started with options `RunConfFromFile test_conf.xlsx working --number 0 --rabbitMQ-host 10.11.3.4 --rabbitMQ-queue whitesharkqueue0 --t true`
3. Sharkfin is started with the options`../../output/whiteshark-babyrunv20_test --simulation Attention --tag tag --seed 92975 --popn 25 --quarters 8 --runs 60 --attention 0.01 --dphm 20000 --market ClientRPCMarket --dividend_growth_rate 1.0 --dividend_std 0.011988 --queue whitesharkqueue0 --rhost 10.11.3.4 --p1 0.01 --p2 0.05 --d1 0.1 --d2 0.1`

locally we would run:

1. `python make_single_config.py --seed 92975 --name test_conf.xlsx --days 120` (i removed the --out-dir so the resulting config is outputted in the current dir) in ammps_config_generator to make the ammps config.
2. `dotnet amm.engine.dll RunConfFromFile [path to test_conf_0.xlsx] working --number 0 --rabbitMQ-host localhost --rabbitMQ-queue whitesharkqueue0 --t true` in amm.engine/amm.engine/bin/Release/net6/ in ammps to start ammps
3. `python run_any_simulation.py [output_path/whiteshark-babyrunv20_test] --simulation Attention --tag tag --seed 92975 --popn 25 --quarters 8 --runs 60 --attention 0.01 --dphm 20000 --market ClientRPCMarket --dividend_growth_rate 1.0 --dividend_std 0.011988 --queue whitesharkqueue0 --rhost localhost --p1 0.01 --p2 0.05 --d1 0.1 --d2 0.1` in simulate/ in sharkfin to start the whiteshark simulation.

This should reproduce the error as in the container

**Testing new behavior**

To test the new behavior where ammps sends a dictonary and handles the errors we need to checkout the current ammps master branch, and the

**Comment by mesalas** [comment]
@sbenthall 
I have compiled a new set of binaries that should respond with a message containing a dictionary and handle the errors, and put them in the [error_reporting](https://github.com/mesalas/ammps_sharkfin_container/tree/error_reporting) branch.

**Comment by sbenthall** [comment]
I see.

One thing that would make this easier would be if `run_any_simulation.py` could take an optional argument, which is a pointer to a YAML config file, which it then unpacks into the command line arguments.

I can't see any downside to adding this. It would be easier to do if you could point me to the code doing the equivalent step in the container generator.

I'll be able to continue working on this issue locally once you can point me to an ammps_sharkfin_container branch with binaries that have the new dictionary market output.

**Comment by gms158** [comment]
Seb-
Not sure if the is helps, but under my sharkfin fork, in the cloud folder, I have all of the yaml generator code.
-Gary

**Comment by gms158** [comment]
Actually, give me ten minutes, the latest updated chum and whiteshark file need pushed to this fork.
-Gary

**Comment by gms158** [comment]
Ok, they should be there now.
-Gary

**Comment by sbenthall** [comment]
That helps thanks @gms158  @mesalas

**Comment by sbenthall** [comment]
The ClientRPCMarket now can accept a JSON response from the RPC pipeline.

https://github.com/sbenthall/SHARKFin/commit/eb702894df1b6790e3ea642641b0b477ea6045f5

It reads the price from the JSON and proceeds normally. It can also handle the case where the response is just a number, as before. So you can merge the `error_reporting` branch to master whenever you are ready.

It does not yet know how to deal intelligently with a `'MarketState':'Stopped'` signal. I have not yet been able to get such a signal from AMMPs. I was able to causae AMMPS to fail, see this issue:

https://github.com/mesalas/ammps_sharkfin_container/issues/8

But with this error AMMPS just crashes; it does not return a market state.

**Comment by mesalas** [comment]
@sbenthall ok. can you post the yaml config or command line args  that produces the error. Also does ammps spit something out or does it just hang. I can run it in the debugger and see how we handle it.

**Comment by mesalas** [comment]
Right maybe I should just read the post 🤦‍♂️

**Comment by sbenthall** [comment]
Ok, I have now pushed changes to master that I think address this problem.

Unfortunately, I have not been able to test my fix.
When I have tried to set the parameters of an AttentionSimulation so that they break the market, I've gotten a simulation that just hangs there unresponsively with no printouts.

It's a serious problem that we don't have an automated way to test SHARKFin and AMMPS together.
The fact that the setup has three manual commands, with many finicky arguments, and then the test itself can take a seemingly arbitrary amount of time to execute, makes development extremely difficult. I frankly just don't have the time to babysit this sort of process every time I need to make a small change.

#127 has been sitting for some time, but now I think it's the highest priority ticket.
