### ISSUE TITLE
Better shutdown sequence for ammps and sharkfin 

### ISSUE THREAD

**Issue by mesalas** [sbenthall/SHARKFin#168]
I think our current shutdown sequence is causing some problems and Id like to propose a more clean solution.
My suggested sequence is as follows:

Say we  want to simulate T days. Currently we send a shutdown signal to ammps after T days have been simulated. I think in some cases this can cause ammps to finish its simulation because it finishes to process its data before receiving the signal. Another possible case is that shakfin sends the shutdown signal but close the connection (and maybe the queue?) before ammps it able to grab it.

Instead I suggest we send the shutdown signal along with buy and sell targets for day T. Instead of shutting down upon receiving the signal it will run the day, and only after sending the result of day T it will initiate the shutdown sequence. In stead of thinking of the shutdown signal as an "off switch" that  halts the simulation we can think of it an a flag telling ammps that we are on the final day of the sim and to halt once the result of that day has been sent.

**Comment by mesalas** [comment]
@sbenthall I have taken a quick [stab](https://github.com/sbenthall/SHARKFin/commit/e041aeddf7762552ee5c3a23190b2f8b3031533e) at implementing the sequence described above and It seems to work with [ammps](https://github.com/ZDavid/amm.engine/commit/672e1277c803f13882fbde751ab79a1c3660ef50).

Im not super happy about the solution as it moves the logic for closing the connection into the trade function, also it will not work if the `runs_per_day`is not 60, but I think the way we shot down is much more clean. Id like to do some tests with @gms158  to see if it removes some of the issues we been having when we shut down.

**Comment by gms158** [comment]
@sbenthall , ok so rebuild master, and then what DOE to use to test ? the previous run, but with just 3 replicates ?

**Comment by sbenthall** [comment]
@gms158 No, not quite....

Check in with @mesalas about this. But the key is to use the `i168` branch of SHARKFin and the [sharkfin_i168](https://github.com/ZDavid/amm.engine/compare/sharkfin_i168) branch of `amm.engine` -- I'm not sure how to get the binary for that into the container. But a special container needs to be built to test this, since the changes have not been merged to master yet. (We are still checking to see if this solves anything).

Let's try testing with the new grid for Whiteshark, which is:

8 quarters, and:

- DPHM : [1000, 5000, 10000, 15000]
- dividend_growth_rate : [1.00, 1.0005, 1.0015]
- attention : [0.05, 0.35, 0.70, 0.95]
- p1 : [0.01, 0.1, 0.5, 0.99]
- p2: [0.01, 0.1, 0.5, 0.99]

But since that is already a big grid, just use _1_ sample per point.

**Comment by gms158** [comment]
@mesalas @sbenthall : the above sharkfin_i168 link results in a 404 error for me. Can you direct me to another link with the ammps binaries ? , or can you create or updated branch in your 
ammps_sharkfin_container project with the updated binaries

**Comment by sbenthall** [comment]
@mesalas to make a new branch of the container repo with the sharkfin_i168

**Comment by mesalas** [comment]
@gms158 Theres a branch in the [ammps_sharkfin_container](https://github.com/mesalas/ammps_sharkfin_container/tree/sharkfin_i168) repository with these changes. You should be able to test this by pulling the branch and building the container.

**Comment by gms158** [comment]
ok, started run on azure, Bill is running the same run in parallel, if results are the same, we can transition and run using Bill's slurm approach since it is faster and cheaper

**Comment by sbenthall** [comment]
We ran this experiment and it did not solve the Error 3 issue. Something else is going on, and we won't merge these changes.
