### ISSUE TITLE
"Pad" simulation with trading days

### ISSUE THREAD

**Issue by nicksawhney** [sbenthall/SHARKFin#70]
In order to run the Chum experiment we need to allow for 30 days of trading with buy/sell orders of zero. This is best achieved by making this a configurable option in the AttentionSimulation class (rather than doing it manually with the market class in a script). This will also allow us to log prices. The question is -- should the HARK agents be doing anything with the price information during those 30 days or should this simply be the market forcing buy/sell orders in.

**Comment by nicksawhney** [comment]
One issue I'm running into is that this would make the buy/sell history and prices lists different lengths from the rest of the history data. Should these values all be padded with 0? @sbenthall please advise.

**Comment by sbenthall** [comment]
In my opinion, for the Chum experiment it would be better to make a new class "next to" the AttentionSimulation.

As we've done with the Market classes, we should have an abstract Simulation class and subclass it to AttentionSimulation and something else, maybe CalibrationSimulation.

Then, think through carefully what is shared by the two simulations.

To answer your question more specifically -- rather than padding the AttentionSimulation process without engaging the rest of the simulation machinery, a 'warmup' trading day could be implemented by passing (0,0) buy/sell limits to the Broker and then keeping track of the history as is done normally.

(If we want to wrap this in something that makes it easier to run an arbitrarily long warmup period, then the tracked history could be truncated from the beginning at the end of the simulation.)

**Comment by nicksawhney** [comment]
I've got code for this ready, but there is a bug. Agents need to have a list of shares to calculate risky expectations, which needs to be done to maintain the expected_ror and expected_std lists for the duration of the simulation (this data from the market stabilization time can be thrown away). This means the agents still solve for each trading day during the calibration time. Does this interfere with the agents in a way that invalidates the simulation data from once they begin trading as normal? If it does not, the fix is relatively simple: the CalibrationSimulation has to call the `compute_share_demand` method before it starts running.

**Comment by sbenthall** [comment]
Maybe I'm missing something, but I don't think CalibrationSimulation needs
HARK agents at all.

On the Nth day, the simulation just needs to pass the parameters from the
configuration straight through to the Broker, then run the market.

**Comment by sbenthall** [comment]
TODO on this: Please add an automated test for the CalibrationSimulation that tests for the right pattern of buy/sell over time (0,0,0,0,0..... 1000/1000).

I will then start refactoring the simulation code, which I'll address in a separate ticket.

**Comment by sbenthall** [comment]
This is fixed now, right, @nicksawhney ?

**Comment by nicksawhney** [comment]
This has been addressed in various PRs over the past few weeks including #87
